version: '3.8'
services:
  petclinic:
    build: .
    image: petclinic
    container_name: petclinic
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING
      - SPRING_PROFILES_ACTIVE
      - MYSQL_URL
    networks:
      - petclinic
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - petclinic
networks:
  petclinic: